version: '2'
services:
  web:
    image: baffedu/aproxy
    volumes: 
      - ./code/:/var/www/html/
    networks: 
      baff:
    environment: 
      - TYPE=others
    ports: 
      - 80:80

networks:
  baff:
    external: true
